name: CD
on:
  push:
    branches: [ main ]

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Zamiana repository_owner na maÅ‚e litery
    - name: Set lowercase owner
      run: |
        echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
      env:
        OWNER: ${{ github.repository_owner }}

    - name: Login to GHCR
      run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push
      run: |
        IMAGE="ghcr.io/${OWNER_LC}/python-app:latest"
        echo "Building image: $IMAGE"
        docker build -t $IMAGE .
        docker push $IMAGE
